version: '3'
services:
  app:
    container_name: dlm-appserver
    build:
      context: ./app
      dockerfile: Dockerfile
    working_dir: /app
    command: realize start --run --no-config
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
    links:
      - 'db'
  db:
    container_name: dlm-db
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: library_manager
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - db-store:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-store:

