settings:
  legacy:
    force: false
    interval: 0s
server:
  status: true
  open: false
  port: 5002
  host: localhost
schema:
- name: datum-library-manager-server
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    - html
    - yml
    - yaml
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
